/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx}', './public/index.html'],
  theme: {
    extend: {
      /* Tablet uses mobile shell until 1024px; desktop grids widen at 1280px */
      screens: {
        md: '1024px',
        lg: '1280px',
      },
      colors: {
        secondary: '#1d5abc',
        primary: '#001e59',
        'on-secondary-fixed': '#001943',
        'on-secondary-fixed-variant': '#004299',
        'on-error-container': '#93000a',
        'surface-tint': '#3d5ba8',
        'tertiary-container': '#483516',
        'on-primary-container': '#839ff1',
        'surface-variant': '#e0e3e5',
        'on-tertiary-fixed': '#281800',
        'surface-container-high': '#e5e9eb',
        'on-tertiary-container': '#ba9d76',
        'surface-container-highest': '#e0e3e5',
        'primary-fixed': '#dbe1ff',
        'on-surface-variant': '#444651',
        'secondary-container': '#6899fe',
        'tertiary-fixed-dim': '#e0c298',
        'primary-container': '#0d337f',
        background: '#f7fafc',
        tertiary: '#312004',
        'primary-fixed-dim': '#b3c5ff',
        'secondary-fixed': '#d9e2ff',
        'surface-dim': '#d7dadc',
        'outline-variant': '#c4c6d3',
        'on-surface': '#181c1e',
        'on-secondary-container': '#003072',
        error: '#ba1a1a',
        'on-primary-fixed': '#001849',
        'inverse-on-surface': '#eef1f3',
        'surface-bright': '#f7fafc',
        'surface-container': '#ebeef0',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#afc6ff',
        'error-container': '#ffdad6',
        'inverse-primary': '#b3c5ff',
        'on-tertiary-fixed-variant': '#584323',
        'on-primary-fixed-variant': '#22428e',
        'on-background': '#181c1e',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3133',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f1f4f6',
        surface: '#f7fafc',
        outline: '#747682',
        'tertiary-fixed': '#fedeb2',
        'on-primary': '#ffffff',
        'decoration-gold': '#C5A880',
        'accent-gold': '#C5A880',
        'deep-navy': '#0D337F',
        'energetic-cobalt': '#1A56DB',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'column-gap': '32px',
        unit: '4px',
        'margin-mobile': '20px',
        gutter: '24px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'display-lg': ['"Libre Caslon Text"', 'serif'],
        'headline-md': ['"Libre Caslon Text"', 'serif'],
        'headline-lg': ['"Libre Caslon Text"', 'serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
